### ISSUE TITLE
Cannot import the library

### ISSUE THREAD

**Issue by sledorze** [tomasdeml/lenticular.ts#10]
When import like so:

`import { pathFromExpression, lensFromPath } from 'lenticular.ts';
`

Typescript compiler (2.0.8) complains with:
"An import path cannot end with a '.ts' extension"

**Comment by tomasdeml** [comment]
Thank you for the report, I will look at it. I may have to republish the package as "lenticular-ts" if this cannot be solved somehow.

**Comment by sledorze** [comment]
Indeed, I think it will prevent useless friction.

**Comment by sledorze** [comment]
@tomasdeml thanks! :)
